### PR TITLE
replace quadratic step with access to linear array

### PR DESCRIPTION
**Pull request by subwaystation**
This PR explores our quadratic visiting steps problem.

### CODE REVIEW

**Comment by subwaystation** [comment]
## Testing on yeast
I ran it two times on `pg1`. 
### master
```
        Command being timed: "smoothxg -t 28 -g 27nov2020/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.seqwish.gfa -w 30000 -I 0.5 -j 5000 -e 5000 -l 10000 -m test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.smooth.maf -s test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.consensus -a -C 10,100,1000,10000 -o test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.smooth.gfa -n"
        User time (seconds): 1284.81
        System time (seconds): 1658.03
        Percent of CPU this job got: 593%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 8:15.48
        Maximum resident set size (kbytes): 3929980
        Exit status: 0
        Command being timed: "smoothxg -t 28 -g 27nov2020/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.seqwish.gfa -w 30000 -I 0.5 -j 5000 -e 5000 -l 10000 -m test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.smooth.maf -s test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.consensus -a -C 10,100,1000,10000 -o test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.smooth.gfa -n"
        User time (seconds): 1304.18
        System time (seconds): 1622.66
        Percent of CPU this job got: 589%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 8:16.36
        Maximum resident set size (kbytes): 3890256
        Exit status: 0        
``` 

### fix_quadratic_consensus_graph
```
        Command being timed: "smoothxg_ -t 28 -g 27nov2020/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.seqwish.gfa -w 30000 -I 0.5 -j 5000 -e 5000 -l 10000 -m test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.smooth.maf -s test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.consensus -a -C 10,100,1000,10000 -o test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.smooth.gfa -n"
        User time (seconds): 1310.69
        System time (seconds): 1627.99
        Percent of CPU this job got: 587%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 8:20.06
        Maximum resident set size (kbytes): 3887928
        Exit status: 0
                Command being timed: "smoothxg_ -t 28 -g 27nov2020/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.seqwish.gfa -w 30000 -I 0.5 -j 5000 -e 5000 -l 10000 -m test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.smooth.maf -s test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.consensus -a -C 10,100,1000,10000 -o test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.smooth.gfa -n"
        User time (seconds): 1319.95
        System time (seconds): 1616.15
        Percent of CPU this job got: 582%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 8:23.89
        Maximum resident set size (kbytes): 3847272
        Exit status: 0
```

Surprisingly, there is basically no difference in elapsed time or memory consumption. 
Will try again on the Chr20 data. By nose, I don't expect a difference.

**Comment by AndreaGuarracino** [comment]
The reason could be that there aren't too many paths in the cerevisiae example. 🤞

**Comment by subwaystation** [comment]
We are trying to get rid of the quadratic visiting of all path steps in the graph.
Currently, we visit `path steps * path steps`. We only want to visit all path steps once. I expect the number of path steps to be performance-critical.

**Comment by subwaystation** [comment]
## Testing on yeast again
I ran it two times on `pg1`. 
### master
```
Command being timed: "smoothxg -t 28 -g 27nov2020/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.seqwish.gfa -w 30000 -I 0 -j 5000 -e 5000 -l 10000 -m test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.smooth.maf -s test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.consensus -a -C 10,100,1000,10000 -o test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.smooth.gfa -n"
        User time (seconds): 1298.54
        System time (seconds): 1837.02
        Percent of CPU this job got: 652%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 8:00.19
        Maximum resident set size (kbytes): 4872588
        Exit status: 0
Command being timed: "smoothxg -t 28 -g 27nov2020/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.seqwish.gfa -w 30000 -I 0 -j 5000 -e 5000 -l 10000 -m test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.smooth.maf -s test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.consensus -a -C 10,100,1000,10000 -o test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.smooth.gfa -n"
        User time (seconds): 1265.95
        System time (seconds): 1832.18
        Percent of CPU this job got: 642%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 8:01.87
        Maximum resident set size (kbytes): 4922060
        Exit status: 0 
```
### fix_quadratic_consensus_graph
```
Command being timed: "smoothxg_ -t 28 -g 27nov2020/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.seqwish.gfa -w 30000 -I 0 -j 5000 -e 5000 -l 10000 -m test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.smooth.maf -s test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.consensus -a -C 10,100,1000,10000 -o test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.smooth.gfa -n"
        User time (seconds): 1306.47
        System time (seconds): 1825.15
        Percent of CPU this job got: 655%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 7:57.64
        Maximum resident set size (kbytes): 4942192
        Exit status: 0
Command being timed: "smoothxg_ -t 28 -g 27nov2020/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0.5-N.seqwish.gfa -w 30000 -I 0 -j 5000 -e 5000 -l 10000 -m test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.smooth.maf -s test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.consensus -a -C 10,100,1000,10000 -o test_quadratic/cerevisiae.pan.fa.gz.pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0-N.smooth.gfa -n"
        User time (seconds): 1283.89
        System time (seconds): 1915.30
        Percent of CPU this job got: 657%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 8:06.90
        Maximum resident set size (kbytes): 4757328
        Exit status: 0
```

Again, surprisingly, there is basically no difference in elapsed time or memory consumption. 
My theory is that the computational resources required during this specific step in the consensus graph generation are so small, that we can't notice the difference. 

If there are no objections @ekg @AndreaGuarracino I would merge this anyhow. From a coder's point of view, this makes more sense.

**Comment by AndreaGuarracino** [comment]
If anything quadratic is removed, I would expect at least a slight performance improvement. Maybe, in the yeast example, the consensus paths aren't enough, or long enough, in terms of steps, to detect differences? What about the chr20?

Here we are removing a `for_each_step_on_handle` loop. I would like to see if something changes when there are much more paths (high depths), so much more possible steps given each handle.

**Comment by ekg** [comment]
When there are a lot of paths, this should be a problem. Right now, you
have a coverage of just a few fold. In the human chr20 case we have ~200x.

**Pull request merged**
