### PR TITLE
mash-based block split

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
This PR makes it possible to split blocks that took weeks in a few hours (or that tooks hours in a few minutes). This is achived applying a mash-based clustering, which is a probabilistic approach. It is absurdly fast, but the cost is that the estimated sequence identity is noisy for medium identical sequences (the estimate improves for 90/95% identical sequences). For this reason, such mash-based clustering is applied for blocks that have a high depth (settable as a parameter), on sequences of minimum length (settable as a parameter).

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
**Tricky human chr20 dataset**

Base command

```smoothxg -g hppy1+h38-chr20.fa.pggb-s50000-p85-n20-a85-K16-k19-w50000-j5000-e5000.gfa -o smooth.gfa -t 20 -n```

```
-I 0.5
cutting and splitting 417848 blocks: elapsed: 00:00:00:48
-I 0.6
cutting and splitting 417848 blocks: elapsed: 00:00:02:03 
-I 0.7
cutting and splitting 417848 blocks: elapsed: 00:00:01:11
-I 0.8
cutting and splitting 417848 blocks: elapsed: 00:00:24:55
-I 0.9
cutting and splitting 417848 blocks: elapsed: 00:00:42:28
-I 0.95
cutting and splitting 417848 blocks: elapsed: 00:00:38:03
-I 0.95 -D 5000
cutting and splitting 417848 blocks: elapsed: 00:00:37:53

-I 0.95 -w 50000 -j 5000 -e 5000 -D 5000
cutting and splitting 117712 blocks: elapsed: 00:00:24:21
```

Some of these commands took hours before. In particular, the last one was intractable: it took a week before killing it.

**Comment by ekg** [comment]
:fire:

**Comment by AndreaGuarracino** [comment]
After the last changes, the timings are improved. The new containment metric (`-R` not equals to 0) takes more time, as expected, because to check if a short sequence is contained in a longer one, the alignment can't be always avoided.

**Tricky human chr20 dataset**

Base command

```smoothxg -g hppy1+h38-chr20.fa.pggb-s50000-p85-n20-a85-K16-k19-w50000-j5000-e5000.gfa -o smooth.gfa -t 20 -n```

```
-I 0.7
cutting and splitting 417848 blocks: elapsed: 00:00:01:24
-I 0.8
cutting and splitting 417848 blocks: elapsed: 00:00:05:10
-I 0.8 -R 0.5
cutting and splitting 417848 blocks: elapsed: 00:00:23:46
-I 0.9
cutting and splitting 417848 blocks: elapsed: 00:00:04:23
-I 0.95
cutting and splitting 417848 blocks: elapsed: 00:00:04:53
-I 0.95 -R 0.5
cutting and splitting 417848 blocks: elapsed: 00:00:31:49

-I 0.95 -w 50000 -j 5000 -e 5000
cutting and splitting 117712 blocks: elapsed: 00:00:24:01
-I 0.95 -w 50000 -j 5000 -e 5000 -D 15000
cutting and splitting 117712 blocks: elapsed: 00:00:24:47
-I 0.95 -w 50000 -j 5000 -e 5000 -D 20000
cutting and splitting 117712 blocks: elapsed: 00:00:23:50
```

**Comment by AndreaGuarracino** [comment]
The remaining tests, showing that the mathematical constraints applied in this PR reduce the split time.

**Tricky human chr20 dataset**

```
-I 0.95 -w 50000 -j 5000 -e 5000 -D 30000
cutting and splitting 117712 blocks: elapsed: 00:00:39:55
-I 0.95 -w 50000 -j 5000 -e 5000 -L0
cutting and splitting 117712 blocks: elapsed: 00:04:16:19
```

**Pull request merged**
