### PR TITLE
unleash the merge with loops and flipping blocks

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
This generalize the block merge, managing tricky cases with blocks which presents loop.

**LPA dataset**
```smoothxg -t 16 -g LPA.prep.gfa -a -w 5000 -m smooth.maf -M -J 0 -n -o smooth.gfa```

Master: 26 blocks
LPA prep gfa smooth

Branch: 5 blocks
LPA prep gfa smooth

```smoothxg -t 16 -g LPA.prep.gfa -a -w 5000 -m smooth.maf -M -J 0.5 -n -o smooth.gfa```
Master: 228 blocks
Branch: 97 blocks

```smoothxg -t 16 -g LPA.prep.gfa -a -w 5000 -m smooth.maf -M -J 1 -n -o smooth.gfa```
Master: 283 blocks
Branch: 139 blocks

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
**Yeast dataset**

```smoothxg -t 16 -g Sc+Sp.pan.fpal10k.Y.G50.gfa -a -w 5000 -m smooth.maf -M -J 0 -n -o smooth.gfa```

Master: 123080 blocks
Branch: 124191 blocks

**Comment by AndreaGuarracino** [comment]
**Human chr20 dataset**

*-J 0.5*
```smoothxg -t 16 -g hppy1+chm13+h38-chr20.fa.gz.pggb-s5000-p99-n6-a0-K16-k37-w30000-j5000-e5000-I0.85.seqwish.gfa.prep.gfa -a -w 5000 -m smooth.maf -M -J 0.5 -n -o smooth.gfa```

> Master: 265605 blocks
> Elapsed (wall clock) time (h:mm:ss or m:ss): 1:01:13
> Maximum resident set size (kbytes): 67340428
> 
> Branch: 264215 blocks
> Elapsed (wall clock) time (h:mm:ss or m:ss): 1:04:40
> Maximum resident set size (kbytes): 67639464

*-J 0*
```smoothxg -t 16 -g hppy1+chm13+h38-chr20.fa.gz.pggb-s5000-p99-n6-a0-K16-k37-w30000-j5000-e5000-I0.85.seqwish.gfa.prep.gfa -a -w 5000 -m smooth.maf -M -J 0 -n -o smooth.gfa```

> Master: 170566 blocks
> Elapsed (wall clock) time (h:mm:ss or m:ss): 1:02:48
> Maximum resident set size (kbytes): 68220452
> 
> Branch: 168999 blocks
> Elapsed (wall clock) time (h:mm:ss or m:ss): 1:40:14
> Maximum resident set size (kbytes): 112144144

With the most permessive setting, time and memory requirements increase.

**Comment by AndreaGuarracino** [comment]
**Human tricky chr20 dataset**

*-J 0*
```smoothxg -t 28 -g hppy1+h38-chr20.fa.pggb-s50000-p85-n20-a85-K16-k19-w50000-j5000-e5000.gfa -a -w 5000 -m smooth.maf -M -J 0.5 -n -o smooth.gfa```

> Master: 294894 blocks
> Elapsed (wall clock) time (h:mm:ss or m:ss): 1:36:23
> Maximum resident set size (kbytes): 87010644
> 
> Branch: 281279 blocks (13615 blocks less)
> Elapsed (wall clock) time (h:mm:ss or m:ss): 1:35:24
> Maximum resident set size (kbytes): 85666524

Fortunately, with the most permissive setting, time and memory requirements do not increase always.

**Comment by AndreaGuarracino** [comment]
**Human chr2 dataset**

Stress test (the command leads to 3737428 blocks before merging).

*-J 0 -w 5000*
```smoothxg -t 28 -g hppy1-vs-hg38.mNp90.chr2.fa.gz.pggb-s5000-p99-n6-a0-K16-k31-w60000-j5000-e5000-I0.5-R0.2.seqwish.gfa.prep.gfa -a -w 5000 -m smooth.maf -M -J 0 -n -o smooth.gfa```

> Master: 553755 blocks
> Elapsed (wall clock) time (h:mm:ss or m:ss): 3:41:28
> Maximum resident set size (kbytes): 242691088
> 
> Branch: 510446 blocks (43309 blocks less)
> Elapsed (wall clock) time (h:mm:ss or m:ss): 3:45:05
> Maximum resident set size (kbytes): 242777764

**Comment by AndreaGuarracino** [comment]
**Human chr2 dataset plus 2 references (loopy and flippy merge)**

*-J 1*
```smoothxg -t 28 -g hppy1+chm13+h38-chr2.fa.gz.pggb-s4000-l12000-p98-n6-a0-K16-k29-w180000-j10000-e10000-I0.5-R0.2.seqwish.gfa.prep.gfa -a -w 180000 -j 10000 -e 10000 -I 0.5 -R 0.2 -m smooth.maf -M -J 1 -n -o smooth.gfa```

> Master: 89504 blocks
> Elapsed (wall clock) time (h:mm:ss or m:ss): 2:16:32
> Maximum resident set size (kbytes): 44453812
> 
> Branch: 38151 blocks (51353 blocks less)
> Elapsed (wall clock) time (h:mm:ss or m:ss): 2:22:11
> Maximum resident set size (kbytes): 44455640

*-J 0.7*
```smoothxg -t 28 -g hppy1+chm13+h38-chr2.fa.gz.pggb-s4000-l12000-p98-n6-a0-K16-k29-w180000-j10000-e10000-I0.5-R0.2.seqwish.gfa.prep.gfa -a -w 180000 -j 10000 -e 10000 -I 0.5 -R 0.2 -m smooth.maf -M -J 0.7 -n -o smooth.gfa```

> Master: 88130 blocks
> Elapsed (wall clock) time (h:mm:ss or m:ss): 2:17:39
> Maximum resident set size (kbytes): 44453688
> 
> Branch: 35472 blocks (52658 blocks less)
> Elapsed (wall clock) time (h:mm:ss or m:ss): 2:21:26
> Maximum resident set size (kbytes): 44455744

**Comment by subwaystation** [comment]
Heureka!

**Pull request merged**
