### PR TITLE
Merge blocks/consensus for 'unchopped' consensus graphs

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
This PR manages cases ignored before, such as merging blocks with loops, and cases in which the blocks have to be merged from the right to the left because the paths in them go from right to left.

Merging blocks involves merging consensus sequences, and thus it has an impact on the consensus graphs (more info in #32). This effect can be modulated by specifying the minimum Jaccard index required between 2 blocks so that they can be merged.

Here are some examples on a pre-sorted on the LPA graph.

**No merge**

93 MAF blocks

*LPA.fa.pggb-s50000-p70-n5-a70-K16-k19-w50000-j5000-e5000.consensus.gfa@10000*
LPA fa pggb-s50000-p70-n5-a70-K16-k19-w50000-j5000-e5000 consensus gfa@10000 noMerge

**-J 1.0 (gentle merge)**

24 MAF blocks, of which 7 merged groups
```
Consensus_2-10
Consensus_12-37
Consensus_39-40
Consensus_45-67
Consensus_68-69
Consensus_73-74
Consensus_77-87
```

*LPA.fa.pggb-s50000-p70-n5-a70-K16-k19-w50000-j5000-e5000.consensus.M.J1.gfa@10000*
LPA fa pggb-s50000-p70-n5-a70-K16-k19-w50000-j5000-e5000 consensus gfa@10000 J1

**-J 0.5 (intermediate merge)**
21 MAF blocks, of which 6 merged groups
```
Consensus_2-10
Consensus_12-37
Consensus_38-40
Consensus_45-69
Consensus_73-74
Consensus_77-88
```

*LPA.fa.pggb-s50000-p70-n5-a70-K16-k19-w50000-j5000-e5000.consensus.M.J05.gfa@10000*
LPA fa pggb-s50000-p70-n5-a70-K16-k19-w50000-j5000-e5000 consensus M gfa@10000 J05

**-J 0.001 (aggressive merge)**

9 MAF blocks, of which 6 merged groups
```
a blocks=0 loops=false
a blocks=1-10 loops=false merged=true below_thresh=true
a blocks=11-37 loops=false merged=true
a blocks=38-44 loops=true merged=true
a blocks=45-72 loops=true merged=true
a blocks=73-74 loops=true merged=true
a blocks=75 loops=false
a blocks=76 loops=true
a blocks=77-91 loops=false merged=true
```

*LPA.fa.pggb-s50000-p70-n5-a70-K16-k19-w50000-j5000-e5000.consensus.M.J0001.gfa@10000*
LPA fa pggb-s50000-p70-n5-a70-K16-k19-w50000-j5000-e5000 consensus gfa@10000 J0001

**-J 0.0 (max aggressive merge)**
7 MAF blocks, of which 5 merged groups
```
a blocks=0-37 loops=false merged=true
a blocks=38-44 loops=true merged=true
a blocks=45-72 loops=true merged=true
a blocks=73-74 loops=true merged=true
a blocks=75 loops=false
a blocks=76 loops=true
a blocks=77-91 loops=false merged=true
```

*LPA.fa.pggb-s50000-p70-n5-a70-K16-k19-w50000-j5000-e5000.consensus.M.J0.gfa@10000*
LPA fa pggb-s50000-p70-n5-a70-K16-k19-w50000-j5000-e5000 consensus M gfa@10000 J0

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
Now, by default, when blocks are merged, the corresponding unmerged consensus sequences are not saved in the MAF output and in the smoothed graph. This leads to smaller MAF output and smaller/simpler smoothed graphs.

```
smoothxg -g LPA.prep.gfa -t 16 -a -w 50000 -j 5000 -e 5000 -l 10000 -m LPA.prep.maf -M -J 0 -n >  LPA.prep.smooth.gfa
```

> LPA.prep.maf: 12 Mb



With the `-N` option, the single consensus sequences are preserved in the MAF output and in the smoothed graph.

```
smoothxg -g LPA.prep.gfa -t 16 -a -w 50000 -j 5000 -e 5000 -l 10000 -m LPA.prep.maf -M -J 0 -n -N >  LPA.prep.smooth.gfa
```

> LPA.prep.maf: 5,7 Mb

**Comment by ekg** [comment]
I ran into a problem when testing.

[x.gfa.txt](https://github.com/pangenome/smoothxg/files/5489998/x.gfa.txt)

```
smoothxg -t 16 -n -g x.gfa -w 50000 -j 5000 -e 5000 -l 10000 -m x.smooth.maf -s x.consensus -M -a -C 10,100,1000,10000 -o x.smooth.gfa
```

I segfault in the consensus generation:

```
[smoothxg::main] loading graph
[smoothxg::main] building xg index
[smoothxg::smoothable_blocks] computing blocks
[smoothxg::smoothable_blocks] computing blocks for 2065 handles: 100.00% @ 8.12e+03/s elapsed: 00:00:00:00 remain: 00:00:00:00
[smoothxg::break_blocks] splitting short sequences out of 4 blocks: 100.00% @ 1.60e+01/s elapsed: 00:00:00:00 remain: 00:00:00:00
[smoothxg::break_blocks] split 0 blocks
[smoothxg::break_blocks] cutting blocks that contain sequences longer than max-poa-length (10000)
[smoothxg::break_blocks] cutting 4 blocks: 100.00% @ 1.60e+01/s elapsed: 00:00:00:00 remain: 00:00:00:00
[smoothxg::break_blocks] cut 0 blocks of which 0 had repeats
[smoothxg::smooth_and_lace] applying global abPOA to 4 blocks: 100.00% @ 5.33e+00/s elapsed: 00:00:00:00 remain: 00:00:00:00
[smoothxg::smooth_and_lace] sorting path_mappings
[smoothxg::smooth_and_lace] adding 4 graphs: 100.00% @ 1.60e+01/s elapsed: 00:00:00:00 remain: 00:00:00:00
[smoothxg::smooth_and_lace] embedding 48 path fragments: 100.00% @ 1.91e+02/s elapsed: 00:00:00:00 remain: 00:00:00:00
[smoothxg::smooth_and_lace] validating 12 path sequences: 100.00% @ 4.79e+01/s elapsed: 00:00:00:00 remain: 00:00:00:00
[smoothxg::smooth_and_lace] sorting consensus
[smoothxg::smooth_and_lace] embedding consensus
[smoothxg::smooth_and_lace] walking edges in 12 paths: 100.00% @ 4.79e+01/s elapsed: 00:00:00:00 remain: 00:00:00:00
[smoothxg::main] smoothed graph length 21093bp in 5803 nodes
[smoothxg::main] writing smoothed graph to x.smooth.gfa
[smoothxg::create_consensus_graph] deriving consensus graph with consensus-jump-max=10
[smoothxg::create_consensus_graph] finding consensus links
[smoothxg::create_consensus_graph] adding consensus paths
[smoothxg::create_consensus_graph] cleaning up redundant link paths
[smoothxg::create_consensus_graph] removing edges connecting the path with a gap less than consensus-jump-max=10
[smoothxg::create_consensus_graph] trimming back link paths
[smoothxg::create_consensus_graph] final graph length 18735bp in 140 nodes
[smoothxg::create_consensus_graph] deriving consensus graph with consensus-jump-max=100
[smoothxg::create_consensus_graph] finding consensus links
[smoothxg::create_consensus_graph] adding consensus paths
[smoothxg::create_consensus_graph] cleaning up redundant link paths
[smoothxg::create_consensus_graph] removing edges connecting the path with a gap less than consensus-jump-max=100
[smoothxg::create_consensus_graph] trimming back link paths
[smoothxg::create_consensus_graph] final graph length 18425bp in 47 nodes
[smoothxg::create_consensus_graph] deriving consensus graph with consensus-jump-max=1000
[smoothxg::create_consensus_graph] finding consensus links
[smoothxg::create_consensus_graph] adding consensus paths
[smoothxg::create_consensus_graph] cleaning up redundant link paths
[smoothxg::create_consensus_graph] removing edges connecting the path with a gap less than consensus-jump-max=1000
[smoothxg::create_consensus_graph] trimming back link paths
[smoothxg::create_consensus_graph] final graph length 14932bp in 8 nodes
[smoothxg::create_consensus_graph] deriving consensus graph with consensus-jump-max=10000
[smoothxg::create_consensus_graph] finding consensus links
[2]    466846 segmentation fault (core dumped)  smoothxg -t 16 -n -g x.gfa -w 50000 -j 5000 -e 5000 -l 10000 -m x.smooth.maf 
```

It's not necessarily a problem with the merging. It could be an issue encountered with a single consensus graph node (as we will have here at 10kb).

**Comment by ekg** [comment]
Perhaps I shouldn't have merged this...

I just ran into a new issue. These merged consensus paths should have been removed, but they weren't.

Screenshot from 2020-11-04 20-24-10

**Comment by AndreaGuarracino** [comment]
@ekg, could you please share the command line and the dataset?

**Pull request merged**
